# #numpy

In [2]:
import numpy as np
np.array(range(10,20))

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [2]:
import numpy as np
np.array(range(10,20,2))

array([10, 12, 14, 16, 18])

In [3]:
np.array(range(9))

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

range and arange is different 
in range array is created where as in arange array is not created.

In [4]:
print(np.arange(5))
print(np.arange(10,5,3))
print(np.arange(2.3,4.5,6.7))
print(np.arange(3,8.9,7))

[0 1 2 3 4]
[]
[2.3]
[3.]


in linspace the third parameter is no.of elements in array.spacing is equal. here  spacing occurs as second parameter -first parameter  and third parameter -1st parameter and then divide both of them.and f u give [1,10,1] that means u need only 1 element in between 1,10. 

In [5]:
print(np.linspace(1,10,5))

[ 1.    3.25  5.5   7.75 10.  ]


In [6]:
import numpy as np
np.ones((5,2),dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

output 6 and 9 are same because 1. any thing means 1 only

In [10]:
o=np.ones((3,4,5))
print(o)
print(o.ndim)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
3


In [24]:
print(a)                                                  ##finding diagonal elements of an array##
np.diag(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]]


array([ 1,  5, 10])

In [22]:
a=np.array([[1,2,3],[4,5,6],[8,9,10]],dtype=int)
a.dtype                                                  #creating a matrix#
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [29]:
print(np.diag([1,2,3]))
print(np.diag([4,5,6]))

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[4 0 0]
 [0 5 0]
 [0 0 6]]


In [ ]:
##random       here when ever we run again and again the output will be different and it will be in between ranges##
*random.randint() only integers values will take and the values wil be in between range.
*random.random(())                      0 to 0.9 values                       
*random.rand()                         ##it takes zeroes and points
*random.randn()                           ##random matrix with -ve no.sit accepts negative values also.
end of the file execution error will come when we do not end (),{},[]

In [34]:
###random###
import numpy as np
print(np.random.randint(10))
print(np.random.randint(3,15))
print(np.random.randint(10,100,(3,5)))

1
11
[[66 86 26 51 49]
 [91 97 71 16 49]
 [51 28 47 19 40]]


In [35]:
print(np.random.rand(2,4))
print('-------------------')
print(np.random.randn(2,4))

[[0.40413432 0.4524539  0.83724842 0.46917227]
 [0.06935663 0.38668253 0.3453327  0.06041067]]
-------------------
[[ 1.45026779 -0.37373303  0.44022283  1.46620091]
 [-0.8975997   0.40925229 -0.86057298 -1.57540767]]


In [36]:
np.random.normal()             #normalizing the normal variable#

0.015707169405749094

##normal is uesd to find mean and distribution of soem nearest values##

In [37]:
np.random.rand(3,4)

array([[0.91570377, 0.88332505, 0.6781042 , 0.51258104],
       [0.81855203, 0.17912901, 0.17532225, 0.63156518],
       [0.37920445, 0.69321663, 0.02125424, 0.98908222]])

In [39]:
a=np.random.randint(10,100,(4,4))    #here the output it will take randomly  and output every time new output will occur
a

array([[59, 35, 74, 33],
       [80, 33, 54, 78],
       [92, 83, 39, 80],
       [76, 67, 86, 97]])

In [40]:
s="kits college"                 #output is second index values
s[2:4]

'ts'

In [52]:
a[2:4,2:4]

array([[39, 80],
       [86, 97]])

In [50]:
s="rizwana"
s[0:1]

'r'

In [46]:
m="rizzu"
m[1:3]

'iz'

In [53]:
a[2:2,2:2]

array([], shape=(0, 0), dtype=int32)

In [54]:
a[2:1,2:1]

array([], shape=(0, 0), dtype=int32)

In [56]:
a[2][2]

39